### ISSUE TITLE
add a Module which need a Configuration

### ISSUE THREAD

**Issue by ghost** [HubSpot/dropwizard-guice#13]
I'm in a case where, in order to initialize injection, one of my modules needs elements from Dropwizard configuration 

The problem is the guiceBundle has to be instanciated at the Bootstrapping phase (Service.initialize() ) and I don't have the Configuration object at this time.

example : 

```
public class MyModule {
     private MyConf conf
     public MyModule(MyConf conf) {
          this.conf = conf;
}

public class MyService {
      public void initialize(final Bootstrap<MyConf> bootstrap) {
          GuiceBundle<MyConf> guiceBundle = GuiceBundle
            .<MyMDBConfiguration> newBuilder()
                .addModule(new MyModule( ** How to pass the conf object here ** ) )
                .setConfigClass(MyConf.class)
                .enableAutoConfig(this.getClass().getPackage().getName())
                .build();
        bootstrap.addBundle(guiceBundle);
    }
}
```

Is it possible to do that using dropwizard-guice ?

**Comment by edrobap** [comment]
Issue #14 is about Managed Objects not Modules.

**Comment by jhaber** [comment]
The first code snippet is accessing the `Configuration` object from within a Guice module though:
```java
public class ApplicationModule extends AbstractModule {
    @Override
    public void configure() {}

    @Provides
    public RedisConfiguration getRedisConfiguration(ApplicationConfiguration configuration) {
        return configuration.getRedis();
    }
}
```
It can't be accessed from inside the `configure` method, but you can access it from a provider method by asking Guice to inject it.

You can also check out [dropwizard-guicier](https://github.com/hubspot/dropwizard-guicier) (a new-and-improved version of dropwizard-guice) that supports this better by letting you extend `DropwizardAwareModule` which lets you access the `Configuration`, `Bootstrap`, and `Environment` directly (for [example](https://github.com/jhaber/dropwizard-guicier-example/blob/50cc51bcec29321aedb64571c8e0bda83e6a7a6b/src/main/java/com/hubspot/dropwizard/example/ExampleModule.java#L21))

**Comment by edrobap** [comment]
The provider method trick didn't work. Tried dropwizard-guicier and it worked. Thanks.
