### ISSUE TITLE
Support ContainerRequestFilters and ContainerResponseFilters

### ISSUE THREAD

**Issue by piersy** [HubSpot/dropwizard-guice#33]
At present I'm storing the injector in a filed inside the application class and then manually registering the request filter in the run method as such.
```
@Override
public void run(RegistrationServiceConfiguration configuration, Environment environment) throws IOException {
environment.jersey().getResourceConfig().getContainerRequestFilters().add(guiceBundle.getInjector().getInstance(DeviceDataExtractionFilter.class));
. . .
}
```

It would be great if this could be auto discovered and injected similarly to the resource classes.

**Comment by yunspace** [comment]
You can also add `@Provider` annotation to your filters since that's what `AutoConfig` looks for. Works pretty well for our use cases. For example:

    @Singleton
    @Provider
    public class CrossDomainFilter implements ContainerResponseFilter {
        private static final int ACCESS_CONTROL_MAX_AGE_IN_SECONDS = 12 * 60 * 60;

        @Override
        public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) throws IOException {
            ....
        }
    }

@HiJon89 If the user has resolved this issue, this should be closed?

**Comment by HiJon89** [comment]
Yup

**Comment by mlk** [comment]
Sorry, do you have an example of this? As I don't see how it works.
