### ISSUE TITLE
Guice unable to create injector for Singletons depending on Configuration or Environment (Redux)

### ISSUE THREAD

**Issue by flavor8** [HubSpot/dropwizard-guice#40]
Referencing #19, unfortunately the solutions provided aren't sufficient / elegant in the case of a singleton that has expensive initialization. Not all singletons can/should be lazily initialized. 

Isn't there a better way to tie into the dropwizard initialization cycle which will solve this?

**Comment by htamas** [comment]
Any update on this?

**Comment by jhaber** [comment]
Since this issue was opened we have introduced dropwizard-guicier which creates the Guice injector during the run phase which solves the problems with eager singletons:
https://github.com/HubSpot/dropwizard-guicier
