### ISSUE TITLE
Question: warning when integrating Governator 

### ISSUE THREAD

**Issue by mastermind1981** [HubSpot/dropwizard-guice#59]
Hi,

I have integrated Governator with Guice Bundle but i'm having this warning / dropwizard (0.8.1): 
```

WARN  [2015-05-23 17:47:36,242] com.netflix.governator.lifecycle.ClasspathScanner: No base packages specified - no classpath scanning will be done
```

Here is how i create the guiceBundle in my module: 

```

    private final GuiceBundle<CarsConfiguration> guiceGovernatorBundle = GuiceBundle.<CarsConfiguration>newBuilder()
            .addModule(this)
            .enableAutoConfig("ma.cars")
            .setConfigClass(CarsConfiguration.class)
            .setInjectorFactory((stage, modules) -> LifecycleInjector.builder()
                    .inStage(stage)
                    .withModules(modules)
                    .build()
                    .createInjector())
            .build();

```

Is this the correct way to integrate Governator with Guice? How could i get rid of the warning?

Thanks in advance,

**Comment by yunspace** [comment]
That warning appears when you are not using Governator's [AutoBinding]( https://github.com/Netflix/governator/wiki/Auto-Binding ) feature. Don't think it's anything to worry about.

**Comment by mastermind1981** [comment]
Oka thank you

**Comment by HiJon89** [comment]
Yeah I don't think this is a dropwizard-guice issue
