### ISSUE TITLE
support filters

### ISSUE THREAD

**Issue by brackxm** [HubSpot/dropwizard-guice#6]
It would be nice to have injection in filters.
For example, allowing

```
environment.addFilter(MyFilter.class, "/*");
```

instead of

```
environment.addFilter(injector.getInstance(MyFilter.class), "/*");
```

**Comment by yunspace** [comment]
You can just add a `@Provider` annotation to your filter. Let `AutoConfig` do the work and no need to meddle around with `environment`. See here #33

**Comment by jhaber** [comment]
I believe what yunspace suggested should work
