### ISSUE TITLE
AVRO support by injecting my own ObjectMapper

### ISSUE THREAD

**Issue by patricioe** [HubSpot/dropwizard-guice#60]
Hi all, great work here.

I'm trying to add avro support to Jersey (which I was able to do directly on Jersey) but for some reason when plugging it in in the Guice Module via GuiceBundle it is not picked up.

In my module I do:
```
public class HelloWorldModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(ObjectMapper.class).toProvider(ObjectMapperProvider.class).in(Singleton.class);
       bind(JacksonJsonProvider.class).toProvider(JacksonAPIJsonProviderProvider.class).in(Singleton.class);
    }
```

It does work (one way - AVRO to JSON) if I do this in the App class during the initialize method:
```bootstrap.getObjectMapper().registerModule(new ObjectMapperProvider.MyModule());```

Could you please advice?

Thanks

**Comment by yunspace** [comment]
Dropwizard core code doesn't use injection for ObjectMapper, it is instantiated in `io.dropwizard.jackson.Jackson.newObjectMapper` with reference stored in both `Bootstrap` and `Environment` classes. You can add Jackson modules to it but you can't overwrite it without replacing a lot of core code.

**Comment by patricioe** [comment]
Thanks for the tip.

**Comment by HiJon89** [comment]
At HubSpot we actually have a lame but effective workaround for this. We gave up on trying to configure dropwizard's `ObjectMapper` the way we want, so instead we use a `Managed` to replace theirs entirely with the one we want to use. The code looks like [this](https://gist.github.com/HiJon89/c289e348aa59ed824e09)

**Comment by patricioe** [comment]
Thank you Jonathan. That makes sense.

**Comment by neilpa** [comment]
@jhaber The gist you linked to is dead. Do you happen to still have an example of this?

**Comment by jhaber** [comment]
Yup, I updated the link
