### ISSUE TITLE
dropwizard 0.8.2

### ISSUE THREAD

**Issue by alexan** [HubSpot/dropwizard-guice#63]
Hello,
when are you planning on supporting dropwizard 0.8.2?

Will you accept an pull request/release a new version if I prepare one?

greetings

**Comment by jhaber** [comment]
I didn't realize it had been released, PR's are very welcome otherwise I can try to get to it later this week

**Comment by alexan** [comment]
did you make any progress? I tried to get this working but failed.

**Comment by jhaber** [comment]
I haven't tried yet, I'll be back in the office in 2 weeks and give it a whirl

**Comment by jhaber** [comment]
Fixed via #65
