### ISSUE TITLE
Resource not a singleton

### ISSUE THREAD

**Issue by gustavkarlsson** [HubSpot/dropwizard-guice#72]
For some reason, my resources aren't injected as singletons, so every request to a resource instantiates a full new object tree for that resource.

Is this expected behavior? Why? And how do I change it?

PS: I'm using enableAutoConfig

**Comment by jhaber** [comment]
This is the [default Guice behavior](https://github.com/google/guice/wiki/Scopes#scopes). You can annotate the resource with `@Singleton` which should cause Guice to bind it as a singleton

**Comment by gustavkarlsson** [comment]
@jhaber Sorry, but I tried that, and it had no effect. I realize it's default behavior in Guice, but does that really make sense as a default for dropwizard resources??

**Comment by jhaber** [comment]
Yes, probably even more so because they are very likely to inject things that are request-scoped, so using `@Singleton` by default would break a huge amount of existing code

**Comment by jhaber** [comment]
As for the scope not being honored, what if you explicitly bind the resource class in a module, something like: `bind(MyResource.class).in(Scopes.SINGLETON)` ?

**Comment by gustavkarlsson** [comment]
@jhaber I ended up with another approach, but yeah, that could have worked. Thanks for the tip.

**Comment by the4yeast** [comment]
@gustavkarlsson what approach did you go with, can you share?

**Comment by alexan** [comment]
annotating the resources with scope annotations is working

**Comment by gustavkarlsson** [comment]
@jhaber I switched to https://github.com/xvik/dropwizard-guicey
