### ISSUE TITLE
Are there plans to add DropWizard 1.0.0 support?

### ISSUE THREAD

**Issue by who** [HubSpot/dropwizard-guice#82]
Are there plans to add DropWizard 1.0.0 support, or is this package mainly for older versions of Dropwizard, i.e. 0.7.x and 0.8.x ?

**Comment by jhaber** [comment]
We will probably add that support to [dropwizard-guicier](https://github.com/HubSpot/dropwizard-guicier) first and possibly backport to dropwizard-guice

**Comment by jhaber** [comment]
I just released dropwizard-guicier [1.0.0.1](http://search.maven.org/#artifactdetails%7Ccom.hubspot.dropwizard%7Cdropwizard-guicier%7C1.0.0.1%7Cjar) which uses dropwizard 1.0.0-rc3. The changes weren't too bad and I think they could get ported to dropwizard-guice

**Comment by heldeen** [comment]
I submitted a PR for this, https://github.com/HubSpot/dropwizard-guice/pull/86, that uses the released dropwizard 1.0.0. Any comments on it are welcome.

**Comment by jhaber** [comment]
Thanks @heldeen I just released version 1.0.0 to Maven central

**Comment by heldeen** [comment]
@jhaber awesome! 🍻
