### ISSUE TITLE
No License inside Jar file

### ISSUE THREAD

**Issue by dhrsharma** [HubSpot/dropwizard-guice#85]
Hi team,

We are planning to use dropwizard-guice for an application but our build has a Nexus IQ scan that checks for License inside the jar and it fails complaining about it. But I do see on Maven central that the  dropwizard-guice carries Apache license. So is there any plan to move license text inside jar files?

**Comment by jhaber** [comment]
If there was something like [this](https://github.com/basepom/basepom/blob/df6ed84e703249dc0f2ba34acecb9ad3143f7f09/oss/pom.xml#L2-L14) in the pom would Nexus IQ pick that up?

**Comment by dhrsharma** [comment]
Cant say until it is scanned. So shall I change it in my fork or dw-guice team will do it in next release?

**Comment by jhaber** [comment]
Can you try that on your fork and if it fixes the issue I'll cut a release with that change

**Comment by dhrsharma** [comment]
Unfortunately I am not allowed to fork any public repo in my work machine, neither I can send that jar from another machine. That is because nexus IQ scan is hosted in work network and I would need this modified artifact on my work machine. For now we will not use dw-guice, so closing this issue.
