### ISSUE TITLE
Deprecated API WARNing in v1.0.0.2

### ISSUE THREAD

**Issue by chrisburke1** [HubSpot/dropwizard-guice#98]
Couldn't find this issue already raised in dropwizard-guice, so thought I'd ask about it.
When starting up my dropwizard app with dropwizard-guice I get the following warning.

WARN  [2016-11-15 20:49:44,414] com.google.inject.servlet.InternalServletModule: You are attempting to use a deprecated API (specifically, attempting to @Inject ServletContext inside an eagerly created singleton. While we allow this for backwards compatibility, be warned that this MAY have unexpected behavior if you have more than one injector (with ServletModule) running in the same JVM. Please consult the Guice Documentation at https://github.com/google/guice/wiki/Servlets for more information.

**Comment by ikatkov** [comment]
For reference - it was fixed in guicier https://github.com/HubSpot/dropwizard-guicier/issues/11

**Comment by jhaber** [comment]
Fixed by #102 thanks @ikatkov

**Comment by ikatkov** [comment]
Would it be possible to release dropwizard-guice-1.0.0.3 now?

**Comment by jhaber** [comment]
Yup, sorry for the delay just released now

**Comment by ikatkov** [comment]
Is there a link to build process? When should I expect to see it in maven?

**Comment by jhaber** [comment]
Ugh my fault, it got pushed to Sonatype staging but I never released it. Just took care of that now, it should show up in Maven central soon
